name: Quality checks

on:
  workflow_call:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "main"
      - "develop"
      - "stage"

jobs:
  lint-and-test:
    uses: otedesco/gh-action-templates/.github/workflows/lint-and-test.yml@main
    secrets: inherit
