name: Quality checks

on:
  workflow_call:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "main"
      - "develop"
      - "stage"

jobs:
  lint-and-test:
    uses: otedesco/gh-action-templates/.github/workflows/lint-and-test.yml@b0bd33051b7b5b8ebe0a8f5a1c588ea0d466ed2d # central quality workflow release 2026-09-02
    secrets: inherit
