name: Quality checks

on:
  workflow_call:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "main"
      - "develop"
      - "stage"

jobs:
  lint-and-test:
    uses: otedesco/gh-action-templates/.github/workflows/lint-and-test.yml@dc35994d4f78f96059e0a13008e04d12c2ad51f9 # central coverage gate release 2026-09-02
    secrets: inherit
