name: Release Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".changeset/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quality-checks:
    uses: otedesco/gh-action-templates/.github/workflows/lint-and-test.yml@5024403d1e4eaf9a26603fb71773a5260ea5f370 # central coverage report compatibility release 2026-09-03
    secrets: inherit
  release-packages:
    needs: [quality-checks]
    uses: otedesco/gh-action-templates/.github/workflows/release-package.yml@5024403d1e4eaf9a26603fb71773a5260ea5f370 # central coverage report compatibility release 2026-09-03
    secrets: inherit
