name: Release Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".changeset/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quality-checks:
    uses: otedesco/gh-action-templates/.github/workflows/lint-and-test.yml@main
    secrets: inherit
  release-packages:
    needs: [quality-checks]
    uses: otedesco/gh-action-templates/.github/workflows/release-package.yml@main
    secrets: inherit
