name: Release Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".changeset/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quality-checks:
    uses: otedesco/gh-action-templates/.github/workflows/lint-and-test.yml@c634d37a48f18d3640f55e376fc7adff2807e4e6 # central coverage report compatibility release 2026-09-03
    secrets: inherit
  release-packages:
    needs: [quality-checks]
    uses: otedesco/gh-action-templates/.github/workflows/release-package.yml@c634d37a48f18d3640f55e376fc7adff2807e4e6 # central coverage report compatibility release 2026-09-03
    secrets: inherit
